id: PF3094383
initial_creation_type: ocr
source_metadata:
  volumes:
    b70999487a3c4a298e2c399329cfd40f:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: ཤ་ཟ་གནོད་སྦྱིན་མཁའ་འགྲོ་ཀུན་ནས་འཁྱིལ་པའི་རྟོགས་པ་ལས་བྱུང་བའི་གྭ་ཐབས་ཞེས་བྱ་བ།
      total_pages: 1201
      volume_number: 46
